# Generated by Django 4.0.1 on 2022-01-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Auth', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('cvr_img', models.CharField(max_length=500000)),
            ],
        ),
    ]
