# Generated by Django 4.0.1 on 2022-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
